### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_TSBackgroundFetch

### ISSUE THREAD

**Issue by locationguru-git** [transistorsoft/cordova-background-geolocation-lt#934]
## Your Environment
cli packages: (/Users/lg2/Mayur/Dhiraagu_WFM/Dhiraagu_WFM/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-plugin-proxy         : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0
global packages:
    Cordova CLI : 6.5.0 
local packages:
    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0
System:
    Node       : v10.15.3
    OS         : macOS
    Xcode      : Xcode 10.2.1 Build version 10E1001 
    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    npm        : 6.4.1 

## Expected Behavior
Successful build using Xcode : 10.2.1 - MacOS : 10.14.4

## Actual Behavior
Getting Below error while building iOS from Xcode 10.2.1 - MacOS - 10.14.4
- Getting Below Build Error message

ld: warning: Could not find auto-linked framework 'TSBackgroundFetch'
ld: warning: Could not find auto-linked framework 'ApplicationServices'
ld: warning: Could not find auto-linked framework 'DiskArbitration'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TSBackgroundFetch", referenced from:
      objc-class-ref in TSLocationManager(TSLocationManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing All Messages
:-1: Undefined symbol: _OBJC_CLASS_$_TSBackgroundFetch

## Steps to Reproduce
1. Add iOS Platform and add "cordova-background-geolocation-lt" Pluging in our app.
2. Add Plugin: 
  command:  ionic cordova plugin add cordova-background-geolocation-lt
3Run  ionic cordova build iOS  
3. Open Xcode project (workspace) and build app.

## Debug logs
<!-- include iOS / Android logs
ld: warning: Could not find auto-linked framework 'TSBackgroundFetch'
ld: warning: Could not find auto-linked framework 'ApplicationServices'
ld: warning: Could not find auto-linked framework 'DiskArbitration'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TSBackgroundFetch", referenced from:
      objc-class-ref in TSLocationManager(TSLocationManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing All Messages
:-1: Undefined symbol: _OBJC_CLASS_$_TSBackgroundFetch

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
`$ cordova platform`

**Comment by christocracy** [comment]
and:
```
$ cordova plugins
```
Are you using Cocoapods?

**Comment by locationguru-git** [comment]
No We are not using Cocoapods. We are using plugin in cordova.

**Comment by locationguru-git** [comment]
This issue is for iOS platform

**Comment by christocracy** [comment]
If you're not using Cocoapods, don't open the `.xcworkspace`, open the `.xcodeproj`

**Show me the result of**:
```
$ cordova platform
```

**Comment by locationguru-git** [comment]
I have also tried with .xcodeproj and still getting same error.
Find below result of cordova platform:
Installed platforms:
  ios 4.3.1
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  android ~6.1.1
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0

**Comment by christocracy** [comment]
Upgrade your Cordova to >= `7.1.0` (latest is `9.0.0`).  Remove and re-add your ios & android platforms after upgrading.

**Comment by locationguru-git** [comment]
Please share details how can we add this framework using Pod file.
