### ISSUE TITLE
window.BackgroundGeolocation is undefined

### ISSUE THREAD

**Issue by vOrbis-io** [transistorsoft/cordova-background-geolocation-lt#590]
## Your Environment
* Plugin version: 2.8.5
* Platform:  Android
* OS version: 7.1.1
* Device manufacturer / model: Samsung J7
* Cordova version (`cordova -v`): 6.3.1
* Cordova platform version (`cordova platform ls`):
* Plugin config:
<platform name="android">
        <preference name="LICENSE" default="[our license key]" />
        <config-file target="AndroidManifest.xml" parent="/manifest/application">
            <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="$LICENSE" />
        </config-file>

        <preference name="GOOGLE_API_VERSION" default="11.6.0" />
        <framework src="com.google.android.gms:play-services-location:$GOOGLE_API_VERSION"/>
        
        <preference name="APPCOMPAT_VERSION" default="26.1.0" />
        <framework src="com.android.support:appcompat-v7:$APPCOMPAT_VERSION"/>

        <framework src="src/android/build.gradle" custom="true" type="gradleReference" />
        <resource-file src="src/android/libs/tslocationmanager.aar" target="src/android/libs/tslocationmanager.aar" />

        <source-file src="src/android/CDVBackgroundGeolocation.java" target-dir="src/com/transistorsoft/cordova/bggeo" />

        <config-file target="config.xml" parent="/*">
            <feature name="BackgroundGeolocation">
                <param name="android-package" value="com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation"/>
            </feature>
        </config-file>
     </platform>

## Expected Behavior
window.BackgroundGeolocation should work.

## Actual Behavior
window.BackgroundGeolocation is undefined.  The plugin doesn't seem to be loading properly on an android device.

## Steps to Reproduce
run the application through visual studio 2017 and debug it on a device, not an emulator.

## Context
Trying to start the background geolocation plugin to capture gps coords.

**Comment by christocracy** [comment]
The **first** thing you do when something doesn’t work is check your logs.  you’ll likely find an exception being thrown.

```
$ adb logcat
```

**Comment by vOrbis-io** [comment]
Those logs are pretty extensive.  Its dumping out a lot of data, however I don't see any exception being thrown.  Anything in particular that I should be looking for?

**Comment by christocracy** [comment]
Your issue is with `Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.eb>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;`

This plugin in not involved with `webview`.  Google your error.

**Comment by vOrbis-io** [comment]
OK, So I was able to get to a point where now I see these errors when compiling in visual studio:

Warning: Plugin doesn't support this project's cordova version. cordova: 6.3.1, failed version requirement: >=7.1.0
Warning: Skipping 'cordova-background-geolocation-lt' for android

Can you verify for me that the plugin will not work with a cordova version lower than 7.1.0 for android?
It does work with iOS.

**Comment by christocracy** [comment]
```
$ npm install -g cordova@7.1.0
```

**Comment by vOrbis-io** [comment]
Ok, I'll assume that because you are telling me to install cordova 7.1.0, that the android version will, in fact, NOT work with a prior version?
Updating the cordova cli could potentially break other plugins that we are using.

Why does it work with iOS with prior versions?

**Comment by christocracy** [comment]
>Why does it work with iOS with prior versions?

Because the Android plugin takes advantage of new features in cordova that allow one to evaluate variables to load dependency versions, the [google-play-services dependency version](https://github.com/transistorsoft/cordova-background-geolocation-lt#configuring-play-services-version), in particular, helping to solve infamous gradle conflicts with other plugins which also import `play-services / Firebase` dependencies.

>Updating the cordova cli could potentially break other plugins that we are using.

You should have no issues.

**Comment by vOrbis-io** [comment]
Ok, I'll give it a shot.

Thank you for the quick replies.

**Comment by vOrbis-io** [comment]
Ok, Update:

cordova CLI 7.1.0 breaks the build, it looks like visual studio doesn't support external cordova toolsets, see link below:
[https://developercommunity.visualstudio.com/content/problem/155550/global-cordova-710-fails-to-build-for-ios-remote-d.html](https://developercommunity.visualstudio.com/content/problem/155550/global-cordova-710-fails-to-build-for-ios-remote-d.html)

that link references iOS but is the same for android.

Is there any possibility that we could get a version of the plugin that works with cordova 6.3.1?

**Comment by christocracy** [comment]
Why don’t you free yourself of Visual Studio and just build from CLI?  If you’re interested in supporting iOS 11, Android 8, you *must* use the latest version.

**Comment by vOrbis-io** [comment]
FREE LIKE A BIRD!!!!!!!!!!! We moved to VS Code, and it seems to be working, your plugin works good.

Your customer service is as fast as a tesla with PLAID turned on, but needs a little more sugar...

None the less, the purchase was worth it.

Thank you
